# clone_test.py

# imported main function to run a sample test using a real folder of files and sample data
import main

# Sample replacement dictionary list. Thie list contains dictionaries, each dictionary consisting of key value pairs using the following system:
	# key: the term that will be replaced from the original file
	# value: the replacement term that will be found in the updated replacement file
rep_list = [
	{'202847': '202848', 'Room 61': 'Room 62', 'TL-001': 'TL-002', 'SIDINGTYPE': 'wooden', 'CO2DIFF!': '-138', 'INDOORCO2!': '634', 'INDOORTEMP!': '77.1', 'INDOORRH!': '55', 'VOCLEVEL': '0.0', 'CEMPC1!': '7,055', 'CEMPC2!': '2,749', 'CEMPC3!': '709', 'CEMPC4!': '177', 'CEMPC5!': '73', 'CEMPC6!': '46', 'CEMPCTOTAL!': '10,809', 'DUSTELEVATED!': 'non-fibrous dust and skin cell fragments', }, #'ROTNOTE!': 'Note: During the assessment, A-Tech observed dry rot and termite damage on the exterior wood siding of Room 61. In an abundance of caution, A-Tech recommends that the exterior wood siding be repaired in order to prevent and minimize future air quality problems.', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.',
	{'202847': '202849', 'Room 61': 'Room 63', 'TL-001': 'TL-003', 'SIDINGTYPE': 'wooden', 'CO2DIFF!': '-171', 'INDOORCO2!': '601', 'INDOORTEMP!': '76.1', 'INDOORRH!': '60', 'VOCLEVEL': '0.0', 'CEMPC1!': 'PENDING RESAMPLE', 'CEMPC2!': 'PENDING RESAMPLE', 'CEMPC3!': 'PENDING RESAMPLE', 'CEMPC4!': 'PENDING RESAMPLE', 'CEMPC5!': 'PENDING RESAMPLE', 'CEMPC6!': 'PENDING RESAMPLE', 'CEMPCTOTAL!': 'PENDING RESAMPLE', 'DUSTELEVATED!': 'non-fibrous dust and skin cell fragments', }, # 'ROTNOTE!': 'Note: During the assessment, A-Tech observed dry rot and termite damage on the exterior wood siding of Room 61. In an abundance of caution, A-Tech recommends that the exterior wood siding be repaired in order to prevent and minimize future air quality problems.', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.',
	{'202847': '202850', 'Room 61': 'Room 64', 'TL-001': 'TL-004', 'SIDINGTYPE': 'wooden', 'CO2DIFF!': '-181', 'INDOORCO2!': '591', 'INDOORTEMP!': '76.8', 'INDOORRH!': '59', 'VOCLEVEL': '0.0', 'CEMPC1!': '5,439', 'CEMPC2!': '2,249', 'CEMPC3!': '437', 'CEMPC4!': '130', 'CEMPC5!': '41', 'CEMPC6!': '32', 'CEMPCTOTAL!': '8,328', 'DUSTELEVATED!': 'non-fibrous dust and skin cell fragments', }, # 'ROTNOTE!': 'Note: During the assessment, A-Tech observed dry rot and termite damage on the exterior wood siding of Room 61. In an abundance of caution, A-Tech recommends that the exterior wood siding be repaired in order to prevent and minimize future air quality problems.', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 
	{'202847': '202851', 'Room 61': 'Room 65', 'TL-001': 'TL-005', 'SIDINGTYPE': 'wooden', 'CO2DIFF!': '-188', 'INDOORCO2!': '584', 'INDOORTEMP!': '77.5', 'INDOORRH!': '59.8',  'VOCLEVEL': '0.0', 'CEMPC1!': '5,873', 'CEMPC2!': '1,832', 'CEMPC3!': '422', 'CEMPC4!': '80', 'CEMPC5!': '22', 'CEMPC6!': '18', 'CEMPCTOTAL!': '8,247', 'DUSTELEVATED!': 'non-fibrous dust and skin cell fragments', }, # 'ROTNOTE!': 'Note: During the assessment, A-Tech observed dry rot and termite damage on the exterior wood siding of Room 61. In an abundance of caution, A-Tech recommends that the exterior wood siding be repaired in order to prevent and minimize future air quality problems.', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.',
	{'202847': '202852', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 54', 'TL-001': 'TL-006', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-112', 'INDOORCO2!': '660', 'INDOORTEMP!': '77.7', 'INDOORRH!': '58.1', 'VOCLEVEL': '0.0', 'CEMPC1!': '108,986', 'CEMPC2!': '34,959', 'CEMPC3!': '6,949', 'CEMPC4!': '1,730', 'CEMPC5!': '470', 'CEMPC6!': '309', 'CEMPCTOTAL!': '153,403', 'DUSTELEVATED!': 'non-fibrous dust', },
	{'202847': '202853', 'ROTNOTE!': '', 'VOCRECC!': 'Low levels of total VOCs (0.1ppm) were detected in the sampled location. No levels of formaldehyde were detected in the sampled location.', 'Room 61': 'Room 53', 'TL-001': 'TL-007', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-69', 'INDOORCO2!': '703', 'INDOORTEMP!': '76.6', 'INDOORRH!': '45.3', 'VOCLEVEL': '0.1', 'CEMPC1!': 'PENDING RESAMPLE', 'CEMPC2!': 'PENDING RESAMPLE', 'CEMPC3!': 'PENDING RESAMPLE', 'CEMPC4!': 'PENDING RESAMPLE', 'CEMPC5!': 'PENDING RESAMPLE', 'CEMPC6!': 'PENDING RESAMPLE', 'CEMPCTOTAL!': 'PENDING RESAMPLE', 'DUSTELEVATED!': 'non-fibrous dust', },
	{'202847': '202854', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 52', 'TL-001': 'TL-008', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-80', 'INDOORCO2!': '692', 'INDOORTEMP!': '75.9', 'INDOORRH!': '56', 'VOCLEVEL': '0.0', 'CEMPC1!': '92,200', 'CEMPC2!': '27,596', 'CEMPC3!': '6,090', 'CEMPC4!': '1,500', 'CEMPC5!': '429', 'CEMPC6!': '291', 'CEMPCTOTAL!': '128,106', 'DUSTELEVATED!': 'non-fibrous dust', },
	{'202847': '202855', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 51', 'TL-001': 'TL-009', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-197', 'INDOORCO2!': '575', 'INDOORTEMP!': '80.4', 'INDOORRH!': '54.3', 'VOCLEVEL': '0.0', 'CEMPC1!': '93,879', 'CEMPC2!': '28,231', 'CEMPC3!': '5,076', 'CEMPC4!': '1,016', 'CEMPC5!': '297', 'CEMPC6!': '193', 'CEMPCTOTAL!': '128,692', 'DUSTELEVATED!': 'non-fibrous dust', },
	{'202847': '202856', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 41', 'TL-001': 'TL-010', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-131', 'INDOORCO2!': '641', 'INDOORTEMP!': '81.8', 'INDOORRH!': '45.4', 'VOCLEVEL': '0.0', 'CEMPC1!': '14,091', 'CEMPC2!': '5,305', 'CEMPC3!': '1,180', 'CEMPC4!': '409', 'CEMPC5!': '122', 'CEMPC6!': '89', 'CEMPCTOTAL!': '21,196', 'DUSTELEVATED!': 'none of the types of substance types analyzed', },
	{'202847': '202857', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 42', 'TL-001': 'TL-011', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-155', 'INDOORCO2!': '617', 'INDOORTEMP!': '75.9', 'INDOORRH!': '53.6', 'VOCLEVEL': '0.0', 'CEMPC1!': '7,786', 'CEMPC2!': '2,333', 'CEMPC3!': '526', 'CEMPC4!': '152', 'CEMPC5!': '54', 'CEMPC6!': '46', 'CEMPCTOTAL!': '10,897', 'DUSTELEVATED!': 'non-fibrous dust and skin cell fragments', },
	{'202847': '202858', 'ROTNOTE!': '', 'VOCRECC!': 'No levels of VOCs or formaldehyde were detected in the sampled location.', 'Room 61': 'Room 43', 'TL-001': 'TL-012', 'SIDINGTYPE': 'metal', 'CO2DIFF!': '-201', 'INDOORCO2!': '571', 'INDOORTEMP!': '79.3', 'INDOORRH!': '52.9', 'VOCLEVEL': '0.0', 'CEMPC1!': '38,247', 'CEMPC2!': '8,346', 'CEMPC3!': '958', 'CEMPC4!': '129', 'CEMPC5!': '18', 'CEMPC6!': '13', 'CEMPCTOTAL!': '47,711', 'DUSTELEVATED!': 'pollen, non-fibrous dust and skin cell fragments', },
]

# Sample directory that contains word files that will be duplicated and replaced in the cloning process
sample_directory = "C:\\Users\\asa\\Documents\\Automation\\Test GGUSD\\202847 GGUSD Marshall Elem School Rm 61 ACM IAQ Asmt"

# Run the clone folder function using the sample data and sample directory
main.clone_folder(directory=sample_directory, replacement_dict_list=rep_list)

